server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/barisbilgeadam/config-server-repo12.git"
          default-label: main
          skip-ssl-validation: true
          username: barisbilgeadam
          password: ${GIT_JAVA12_KEY}

