server:
  port: 9091

spring:
  security:
    user:
      name: java12
      password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user

  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: user-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: UserProfileDB
      username: defaultUser
      password: bilge!123


authserviceconfig:
  secrets:
    secret-key: ${JAVA12_SECRETKEY}
    issuer:  ${JAVA12_ISSUER}


redisconfig:
  host: localhost
  port: 6379
